version: '2.1'
orbs: 
  aws-cli: circleci/aws-cli@4.1.0
  aws-ecr: circleci/aws-ecr@9.0.0
jobs:
  build-docker-image: 
    parameters:
      image_tag:
        type: string
        default: latest
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - aws-ecr/build_image: 
          attach_workspace: true
            #auth: 
            #- aws-cli/setup: 
            #    role_arn: ${AWS_OIDC_ROLE_ARN}
          dockerfile: Dockerfile
          push_image: true
          repo: ${AWS_ECR_REPO}
          region: us-west-2
          tag: << parameters.image_tag >>
          
  credential-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: cli-access
          role_arn: ${AWS_OIDC_ROLE_ARN}
          region: us-west-2
      - run: 
          name: check-login
          command: | 
            aws sts get-caller-identity
  apply-feature:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: ${AWS_OIDC_ROLE_ARN}
          aws-region: us-west-2
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Bash
          command: |
            apk update
            apk upgrade
            apk add bash
      - run:
          name: terraform init
          command: |
            terraform workspace select ${TF_VAR_env_name}
            terraform init -input=false

workflows:
  on-merge-to-main:
    jobs:
      - credential-setup: 
          context: Test
          filters:
            branches:
              only: main
      - build-docker-image: 
          context: Test
          filters:
            branches:
              only: main
  on-branch-created-or-updated:
    jobs:
      - credential-setup: 
          context: Dev
          filters:
            branches:
              ignore: main
      - build-docker-image: 
          image_tag: << pipeline.git.branch >>
          context: Dev
          filters:
            branches:
              ignore: main
  on-tag:
    jobs:
      - credential-setup: 
          context: Stage
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
